services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_x
    environment:
      - 'POSTGRES_DB=epictask'
      - 'POSTGRES_PASSWORD=epictask'
      - 'POSTGRES_USER=epictask'
    ports:
      - '5432:5432'
